### PR TITLE
HUD Updates

### PR DESCRIPTION
**Pull request by Tiagoquix**
This pull request:

- reverts the changes made to the strings' names. They could conflict with the TF2 base strings, so I added a FH_ to all of them.
- adds `cc_subtitles 0;cc_predisplay_time 0` to the captions toggle. The cc_subtitles ensures everything is shown and cc_predisplay_time removes the delay. They are essential.
- fixes two errors in the closecaption_english.txt file: uses mp3 instead of wav (since the original file uses mp3 in the commentaries) and corrects "Heavy.CloakedSpyIdentify06" using lowercase ("enemy!" -> "ENEMY!").
- adds translated captions in Brazilian Portuguese (with support for Developer Commentaries). I also generated new .dat files for both English and B. Portuguese but the English one seems to have no changes. [I tested and they work fine.](https://cdn.discordapp.com/attachments/683743232659554327/946519722646724668/unknown.png)

### CODE REVIEW

**Comment by Tiagoquix** [comment]
I encountered a problem when testing: the strings of "That X is a Spy" and "That X is an Enemy" in PT-BR were causing the game to crash, in addition to not appearing completely (they were being cut out). I fixed this by editing the hudlayout.res by modifying the "xpos" and "wide" values for the "HudCloseCaption".

[Here is a video demonstrating the captions with the edited file (recorded in the 1366x768 resolution).](https://streamable.com/aayzoj)

This edit also fixed an issue where some strings were being cut off and not displaying all the text and/or were splitting incorrectly.

I just haven't tested the MvM strings, but I don't think there will be any problem with them.

I also took advantage and updated a string to be shorter in PT-BR, making it easier to read.

**Comment by Tiagoquix** [comment]
You can tweak the values in hudlayout.res if you want, but please test the Spy captions using `cc_lang brazilian` before updating the files in the repo.

**Comment by CriticalFlaw** [comment]
Thanks for the caption name correction. Hadn't though of there being a conflict, but it's good to be prepared.

I've reverted the closed caption box position and size changes because then it's bigger than I would like it to be. I've also reverted the closed caption command change because `cc_subtitles` is for sound effects which are not even in the captions and `cc_predisplay_time` will not make a difference to the user with the captions provided. In my testing, I didn't even see a difference between different values.

**Comment by Tiagoquix** [comment]
> Thanks for the caption name correction. Hadn't though of there being a conflict, but it's good to be prepared.
> 
> I've reverted the closed caption box position and size changes because then it's bigger than I would like it to be. I've also reverted the closed caption command change because `cc_subtitles` is for sound effects which are not even in the captions and `cc_predisplay_time` will not make a difference to the user with the captions provided. In my testing, I didn't even see a difference between different values.

If you don't keep the changes about the closed caption box, it will cause a crash while using the Brazilian captions, because they don't render properly. They need more space. Please keep this change.

`cc_subtitles` might omit some captions, doesn't it? I think the voice commands/responses from characters are considered sound effects.

`cc_predisplay_time` does add a 0.25 seconds delay by default. You don't perceive it, but it does. It's important to have it set to 0.

**Comment by CriticalFlaw** [comment]
> 

Very well, I'll add the closed caption change back.

**Comment by Tiagoquix** [comment]
@CriticalFlaw About `cc_predisplay_time`, even clovervidia advertises you to set it to 0. Check his steam guide: https://steamcommunity.com/sharedfiles/filedetails/?id=167785751

Interestingly enough, he also suggests to use `cc_subtitles 1` instead of 0.

**Comment by Tiagoquix** [comment]
> @CriticalFlaw About `cc_predisplay_time`, even clovervidia advertises you to set it to 0. Check his steam guide: https://steamcommunity.com/sharedfiles/filedetails/?id=167785751
> 
> Interestingly enough, he also suggests to use `cc_subtitles 1` instead of 0.

@CriticalFlaw So, what's your opinion on this?

**Comment by Tiagoquix** [comment]
> > 
> 
> Very well, I'll add the closed caption change back.

The current hudlayout.res doesn't fix the problem.
image

Also, why change the ypos? It was already good. The problem relies in xpos and wide.

**Comment by Tiagoquix** [comment]
> @CriticalFlaw About `cc_predisplay_time`, even clovervidia advertises you to set it to 0. Check his steam guide: https://steamcommunity.com/sharedfiles/filedetails/?id=167785751
> 
> Interestingly enough, he also suggests to use `cc_subtitles 1` instead of 0.

] cc_predisplay_time 
 ( def. "0.25" )"cc_predisplay_time" = "0"
 client archive
 **- Close caption delay before showing caption.**

**Comment by Tiagoquix** [comment]
FYI I'm using the Code Pro fonts.

**Comment by Tiagoquix** [comment]
> > > 
> > 
> > 
> > Very well, I'll add the closed caption change back.
> 
> The current hudlayout.res doesn't fix the problem. image
> 
> Also, why change the ypos? It was already good. The problem relies in xpos and wide.

image

**Comment by Tiagoquix** [comment]
Please revert https://github.com/CriticalFlaw/flawhud/commit/95baf653f1d6dbfe3a04599b00b5fe2f9ecd7ef8 and https://github.com/CriticalFlaw/flawhud/commit/67e180cd86169cd4e6e1aa2eb5e0ad344ecfc412.

**Comment by CriticalFlaw** [comment]
> > > > 
> > > 
> > > 
> > > Very well, I'll add the closed caption change back.
> > 
> > 
> > The current hudlayout.res doesn't fix the problem. image
> > Also, why change the ypos? It was already good. The problem relies in xpos and wide.
> 
> image

ypos was changed for the alternate HUD style.

I'll see to adjust the font size and cc positioning to accommodate both font styles.

**Pull request merged**
