### PR TITLE
Change color of chat window to better match and fix bug in the class selection

### PR DESCRIPTION
**Pull request by ossimalvin**
* Changed the base color of the chat window to better match the theme. The filters button, controls, and text are still the same as stock HUD but it's progress I guess.
* There was a bug I encountered when the Random class button in the class selection menu. It seems to be due to some hard code in the control itself. Using the same values on what the game considers a different control (Different name) and disabling the before used control seems to do the trick.

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Could you explain a bit more about what exactly the bug with the Random class selection button is?

**Comment by ossimalvin** [comment]
When the Random button was selected, oftentimes the edit loudout button would disappear and I would have to open and close the class menu to fix it. I don't know what the exact reasoning behind this is but when I gave the button a different name it stopped happening. I can only assume valve attached code to that specific control or added some obscure property to it in the default HUD.

**Comment by CriticalFlaw** [comment]
If I understood you correctly, when you select the _Random_ option from the class selection and then go back to that screen the _Edit Loadout_ option is not there?

**Comment by ossimalvin** [comment]
Yes. Unless I reopen the class menu.

**Comment by CriticalFlaw** [comment]
I'll try to replicate it later tonight and if that's the case, I'll merge your changes in. Thanks!

**Comment by ossimalvin** [comment]
Here ya go. Took some video of it, excuse my french. It could be dependent on aspect ratio/res. I have 16:10 at 1650x1080.
https://www.webmshare.com/mKAB9

**Comment by CriticalFlaw** [comment]
I see what you mean now. I think Valve made that intentionally because you're not supposed to edit loadout for a random class.  But I like your solution though, it's a lot less janky now that Edit Loadout doesn't disappear constantly. Merging it in now, thank you very much for contributing!

**Pull request merged**
