### PR TITLE
I have a practical problem

### PR DESCRIPTION
**Pull request by 69420-cell**
So I have been playing engineer almost since I enter tf2 but here is the thing when I tried your hud is very difficult at least for me to notice that or they are attacking my sentry or sapping it and I want to ask if you could add a repair icon and a sapp icon if the sentry is sapped or attacked

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Is this for Open Fortress or the main TF2? You seemed to have opened a PR to merge OF changes into TF2.

**Comment by 69420-cell** [comment]
> Is this for Open Fortress or the main TF2? You seemed to have opened a PR to merge OF changes into TF2.

No main tf2 it didn't allow me to just put master sorry for the confusion

**Comment by CriticalFlaw** [comment]
ok, I'll transfer this into an issue as pull requests are for merging code changes, not reporting bugs.

**Comment by CriticalFlaw** [comment]
Transferred to https://github.com/CriticalFlaw/FlawHUD/issues/140

**Pull request closed without merging**
