### PR TITLE
mvmwavelosspanel.res rework

### PR DESCRIPTION
**Pull request by TheRSO**
**Before**
image

**After**
image

Changes
Removed restart to vote (friend lost a 7hr 2man to this, on a different hud albeit. Still able to restart via vote menu regardless.)
Increased height Label heights to fix clipping for P,Q, G and capital letters.
Shifted around various elements.

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Definitely looks neater though I'd prefer to not remove the vote button. Not everyone knows or wants to enter a command when a button already exists

**Comment by TheRSO** [comment]
image
image
You don't have to use a command to restart. Removing the restart button on the wave loss panel just keeps it from being front and center where it could be accidentally pressed, it doesn't remove the ability to restart all together.

**Comment by CriticalFlaw** [comment]
I'd suggest to still keep the button in and coloring it red to give people second thought before clicking. Because otherwise soon this goes out someone will report the button missing and say they prefer it there.

**Comment by TheRSO** [comment]
image
image
armed colors
image

Note this color doesn't match the money missed label, but I think that it looks a tad awkward with the pinkish RedSolid
image
image

**Comment by CriticalFlaw** [comment]
Good idea and look. I like it. Thanks!

**Pull request merged**
