### PR TITLE
Add translation support

### PR DESCRIPTION
**Pull request by Tiagoquix**
Using `chat_` files, I changed all FlawHUD's strings to support translations.

As a courtesy, I also added Brazilian Portuguese translations.

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Looks good. Thank you for the PR. Next time, please indicate whether you've tested it or not. Just to help with testing in case there's an issue.

**Comment by Tiagoquix** [comment]
> Looks good. Thank you for the PR. Next time, please indicate whether you've tested it or not. Just to help with testing in case there's an issue.

Oh, sorry. Yes, I tested it and there are no issues.

**Comment by Tiagoquix** [comment]
@CriticalFlaw Remember that you will need to edit chat_english.txt and chat_brazilian.txt for every new supporter or version released. Do you want me to transfer these to the .RES files instead?

**Comment by CriticalFlaw** [comment]
> @CriticalFlaw Remember that you will need to edit chat_english.txt and chat_brazilian.txt for every new supporter or version released. Do you want me to transfer these to the .RES files instead?

Will it default to English if the string is missing in Brazilian?

**Comment by Tiagoquix** [comment]
> > @CriticalFlaw Remember that you will need to edit chat_english.txt and chat_brazilian.txt for every new supporter or version released. Do you want me to transfer these to the .RES files instead?
> 
> Will it default to English if the string is missing in Brazilian?

Yes, but there is also the same string in Brazilian, so you would need to edit the two files.

To avoid this inconvenience, I fixed it in #216.

**Comment by Tiagoquix** [comment]
I also took advantage and translated the string "Favorite Server", which I had forgotten.

**Pull request merged**
