### PR TITLE
Bug fixes and minor visual adjustments

### PR DESCRIPTION
**Pull request by impale1**
### Fixed player destruction flag value shadow being in the wrong place
before
pd_watergate0002
after
pd_watergate0003
### Fixed MsgLabel cutoff (again)
before
tr_target0010
after
tr_target0017
### Fixed displaying of a part of the cart button in the cart panel (again)
before
snapshot0009
after

### Added back countdown to player destruction and robot destruction
rd_asteroid0011
### Added back reactor core meter to robot destruction
rd_asteroid0006
### Added a background for video caption
tr_target0016
### Fixed contracker TipLabel text being cutoff
before
snapshot0011
after
snapshot0015
### Removed unused button in matchmaking ping panel
before
snapshot0014
after
snapshot0018

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Looks good. Only thing is to center the test on the video captions, they are too close to the outer box. If they are already centered then reduce the font size by 1.
image

**Comment by impale1** [comment]
That won't work. The only other solution is to make the main background non-transparent

**Comment by CriticalFlaw** [comment]
What's questmappanel.res and questdefinitionviewpanel.res for?

**Comment by impale1** [comment]
### questmappanel.res
before
snapshot0011
after
snapshot0015
### questdefinitionviewpanel.res
before
snapshot0012
after
snapshot0022

**Comment by CriticalFlaw** [comment]
> ### questmappanel.res
> before snapshot0011 after snapshot0015
> 
> ### questdefinitionviewpanel.res
> before snapshot0012 after snapshot0022

I think both are too niche of issues to justify adding entiry files for. I'd rather Valve fixied it on their end if it's an issue in the default hud.

**Comment by CriticalFlaw** [comment]
> That won't work. The only other solution is to make the main background non-transparent

Added `textinsetx` to move the text away from the edge (fe71f6c643bc0cb27bd9f44439abbcab535c86d9)

**Comment by impale1** [comment]
> > ### questmappanel.res
> > before snapshot0011 after snapshot0015
> > ### questdefinitionviewpanel.res
> > before snapshot0012 after snapshot0022
> 
> I think both are too niche of issues to justify adding entiry files for. I'd rather Valve fixied it on their end if it's an issue in the default hud.

Yeah, turns out both problems are in the default hud as well

**Comment by CriticalFlaw** [comment]
Removed those two files. The rest looks good. Thank you!

**Pull request merged**
