### PR TITLE
Suggestions (PR)

### LINKED ISSUE #212: --- Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing
This error still appears on the console, even with the fix implemented by the HUD.

### LINKED ISSUE #215: Suggestions
Hello. I have some suggestions for things I think should be included in FlawHUD. I know how to do them all, I am just saying talking about them here because first I want to know what is your opinion about them, @CriticalFlaw. If you approve any of them, I will send a pull request accordingly.

1. In `resource/ui/importfiledialog.res`, FlawHUD uses `: Start Time` instead of the default `Start Time:` present in the default HUD. I think you should change that.

2. I think the hit indicator should be a separate `hudanimations_` file inside the `scripts` folder, so people will be able to easily turn it on or off using the hudanimations_manifest.txt file. If this gets approved, then the README should also be changed.

3. In `scripts/hudlayout.res`, I think a comment should be added in the "fgcolor" of "CustomCrosshair" to say something like: "// RGBA", so people will know they can use another color rather than the default value "Crosshair" which looks for a specific color present in the clientscheme.

4. In clientscheme_settings.res, I think you definitely should revert the change to the meter, from gray to black again. I talked about it here: https://github.com/CriticalFlaw/flawhud/pull/197. Personally, I have been using the color black since you made the change, because I really do not like gray in this particular case.

Thanks in advance.

### PR DESCRIPTION
**Pull request by Tiagoquix**
This closes #212 

This closes #215

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Revert https://github.com/CriticalFlaw/flawhud/pull/216/commits/6d7874e9f7ce0e246abadfc77bf91971736c4eec and https://github.com/CriticalFlaw/flawhud/pull/216/commits/7d03823bdc517f55381c26463d615c4657d6916c. I don't accept grammatical changes anymore.

**Comment by Tiagoquix** [comment]
> Revert [6d7874e](https://github.com/CriticalFlaw/flawhud/commit/6d7874e9f7ce0e246abadfc77bf91971736c4eec) and [7d03823](https://github.com/CriticalFlaw/flawhud/commit/7d03823bdc517f55381c26463d615c4657d6916c). I don't accept grammatical changes anymore.

These texts were inserted by me. They are not in the original README.

Compare: https://github.com/CriticalFlaw/flawhud#hud-crosshair and https://github.com/Tiagoquix/flawhud#hud-crosshair

**Comment by Tiagoquix** [comment]
About https://github.com/CriticalFlaw/flawhud/commit/6d7874e9f7ce0e246abadfc77bf91971736c4eec: it is not a purely a grammatical change, it is a change of meaning. You do not need to change both Crosshair and CrosshairDamage, you need to change only one of them. This is the reason behind the change.

About https://github.com/CriticalFlaw/flawhud/commit/7d03823bdc517f55381c26463d615c4657d6916c: I can revert it, no problems. I changed "don't" to "do not" because there is no abbreviations with apostrophes in the original README file.

**Comment by CriticalFlaw** [comment]
I've made changes to the PR to better fit what I had in mind. Best to not couple together so many different changes because if I don't like one out of the bunch then it needs a separate commit to remove.

**Pull request merged**
