### PR TITLE
Adding French localization.

### PR DESCRIPTION
**Pull request by DimitriDR**
Hey,

Here, the French localization.

### CODE REVIEW

**Comment by DimitriDR** [comment]
And BTW, where are the support messages written. It was the only I wasn't able to find...

**Comment by CriticalFlaw** [comment]
It's in the same folder `flawhud/resource/support.res`. Did you want to add translation for those as part of this PR?

**Comment by Tiagoquix** [comment]
> And BTW, where are the support messages written. It was the only I wasn't able to find...

You already translated them.

https://github.com/DimitriDR/flawhud/blob/7610de39517f1451e7e90d8b1e0bb3cf93e8ae07/resource/chat_french.txt#L23
https://github.com/DimitriDR/flawhud/blob/7610de39517f1451e7e90d8b1e0bb3cf93e8ae07/resource/chat_french.txt#L24

Also, remove the extra spaces added in chat_say_team and chat_say_party (after the colons). [The official file doesn't include extra spaces](https://raw.githubusercontent.com/SteamDatabase/GameTracking-TF2/master/hl2/resource/chat_french.txt).

**Comment by DimitriDR** [comment]
> > And BTW, where are the support messages written. It was the only I wasn't able to find...
> 
> You already translated them.
> 
> https://github.com/DimitriDR/flawhud/blob/7610de39517f1451e7e90d8b1e0bb3cf93e8ae07/resource/chat_french.txt#L23 https://github.com/DimitriDR/flawhud/blob/7610de39517f1451e7e90d8b1e0bb3cf93e8ae07/resource/chat_french.txt#L24
> 
> Also, remove the extra spaces added in chat_say_team and chat_say_party (after the colons). [The official file doesn't include extra spaces](https://raw.githubusercontent.com/SteamDatabase/GameTracking-TF2/master/hl2/resource/chat_french.txt).

Yeah 😅
I wasn't clear but I mean, where is this translated sentence in TF2?

For the extra spaces, It's normal, in French, It's the rule to add space before and after ":" (and It is not a problem in-game)

**Comment by DimitriDR** [comment]
> It's in the same folder `flawhud/resource/support.res`. Did you want to add translation for those as part of this PR?

Oh no, no, I meant where is the translated sentence in the game? It doesn't appear in TF2? :O

**Comment by Tiagoquix** [comment]
> I wasn't clear but I mean, where is this translated sentence in TF2?

It isn't. That's why it's in the section "FlawHUD strings" -- that means, custom text inserted by FlawHUD.

> For the extra spaces, It's normal, in French, It's the rule to add space before and after ":" (and It is not a problem in-game)

If the official translation doesn't include them, then you shouldn't.

> Oh no, no, I meant where is the translated sentence in the game? It doesn't appear in TF2? :O

Stats screen.

**Comment by DimitriDR** [comment]
> > I wasn't clear but I mean, where is this translated sentence in TF2?
> 
> It isn't. That's why it's in the section "FlawHUD strings" -- that means, custom text inserted by FlawHUD.
> 
> > For the extra spaces, It's normal, in French, It's the rule to add space before and after ":" (and It is not a problem in-game)
> 
> If the official translation doesn't include them, then you shouldn't.
> 
> > Oh no, no, I meant where is the translated sentence in the game? It doesn't appear in TF2? :O
> 
> Stats screen.

Oh right, thanks, I can't find it but It's okay, I'm confident about all my translations.
For the extra spaces, I see we don't agree so It'll be to the author to judge. 

Honestly, I don't see why I shouldn't include the extra space because:

1. You won't use this.
2. It's the grammar of the rule, I don't decide.
3. It doesn't impact the other languages.
4. It doesn't cause any harm to the HUD.

**Comment by Tiagoquix** [comment]
Again, if the official translation doesn't include them, then you shouldn't.

You can be sure that the French translator team also knows the grammar rules (since you had to pass in a test on the [Steam Translation Server](http://translation.steampowered.com) and demonstrate knowledge of the language), and if they didn't include the extra space then they have a reason for that.

**Comment by DimitriDR** [comment]
What contempt. I'm also on STS by the way so no need to write with this condescension. The reason is not given but I can tell you that it is a syntactic error. I know my own mother tongue anyway. May I say that you make mistakes in Brazilian Portuguese? No.

**Comment by Tiagoquix** [comment]
I'm also a member of the STS, but that's not important here.

I saw the print you sent, and I also saw that you hid it. Know that it is not completely hidden: you have to delete the history of your previous comment (using the "edited" button) to hide/delete it completely.

I'm sorry for the animosity created here, but my intention was to know why you put spaces before and **after** the colons in two strings, but not in the first string of chat_ in the chat_french.txt file.

image

If that's wrong: nice find! Please, take advantage since you're member of the French STS and report this to them.

But I'm almost sure there's no space **after** the colons because the string just appears in a box (in the chat box, before your text) and is separated by a HUD element, so that's why there's no need to keep the extra space **after** the colons.

With "before your text", I mean: before the user typed text (message).

**Comment by DimitriDR** [comment]
> I saw the print you sent, and I also saw that you hid it. Know that it is not completely hidden: you have to delete the history of your previous comment (using the "edited" button) to hide/delete it completely.

I wasn't trying to hide it, I realized I said something stupid because there is no space after the colon on the screenshot, so It was irrelevant.

> but my intention was to know why you put spaces before and after the colons in two strings, but not in the first string of chat_ in the chat_french.txt file.

God. I didn't see that there wasn't on the `chat_say`. 

Okay, so I'll check in-game if there's already a space after, and I'll edit this message. 

After verification, I have the following:

Capture d’écran 2022-04-22 223114

Capture d’écran 2022-04-22 223050

So the extra space after the colon doesn't indeed add any value. I'll make it more consistent by removing it.
And sorry for my animosity but I've had so many ***holes on Github bitching about my PR for no reason, that I'm wary of criticism xD

**Comment by Tiagoquix** [comment]
> > I saw the print you sent, and I also saw that you hid it. Know that it is not completely hidden: you have to delete the history of your previous comment (using the "edited" button) to hide/delete it completely.
> 
> I wasn't trying to hide it, I realized I said something stupid because there is no space after the colon on the screenshot, so It was irrelevant.
> 
> > but my intention was to know why you put spaces before and after the colons in two strings, but not in the first string of chat_ in the chat_french.txt file.
> 
> God. I didn't see that there wasn't on the `chat_say`.
> 
> Okay, so I'll check in-game if there's already a space after, and I'll edit this message.
> 
> After verification, I have the following:
> 
> Capture d’écran 2022-04-22 223114
> 
> Capture d’écran 2022-04-22 223050
> 
> So the extra space after the colon doesn't indeed add any value. I'll make it more consistent by removing it. And sorry for my animosity but I've had so many ***holes on Github bitching about my PR for no reason, that I'm wary of criticism xD

Congratulations on your willingness to check and analyze the problem. You deserve an award.

And as for the animosity created: no problem, I would probably also be pissed off being in your shoes if someone came out of nowhere to talk sh*t about my PR for apparently no reason at all.

Thank you very much, have a great day and thank you for your patience.

**Comment by DimitriDR** [comment]
Thanks, you too :P

**Pull request merged**
