### PR TITLE
HUD Updates

### PR DESCRIPTION
**Pull request by Tiagoquix**
This pull request:

- fixes a grammatical error in `chat_brazilian.txt` (sorry about that, but I had not notice it until now). String updated: `FH_supporters_list`.
- changes the value of `BgAlpha` in `hudlayout.res` in the `HudCloseCaption` section to `128`, to use the same value as the original `hudlayout.res`.

### CODE REVIEW

**Comment by Tiagoquix** [comment]
By the way, taking advantage of this pull request (even if it is rejected), I would like to ask: when are you planning to release a new version of FlawHUD to include the latest changes?

**Comment by Tiagoquix** [comment]
Also, I do not even think this is important now, but there is a incorrect patch note in the latest FlawHUD version:

> Converted audio files to .wav to save space.

The files were actually converted to .mp3 (they were .wav files), as seen here: https://github.com/CriticalFlaw/flawhud/commit/d3ae5197efee6ffe7757dd4f86a6a9db7632607d

**Comment by Tiagoquix** [comment]
You might want to take a look at this before releasing a new version: https://github.com/JarateKing/BaseHud/blob/master/resource/chat_update_all_to_english.bat

As I understand it, the game will display invalid strings if they are not present in files for other languages.

This .bat will make all chat_english.txt strings present in other languages as well. The only downside is that this will necessarily leave the chat in English for people playing in other languages (and this also sets the "Language" token in all files to "English", but I do not know if this causes problems).

For instance, this is used by budhud.

**Comment by Tiagoquix** [comment]
The solution to avoid the chat being in English in all languages would be to open each file of each language and copy the corresponding strings and then leave the English strings from FlawHUD, but this will require manual work. Would you like me to do this for you?

**Comment by CriticalFlaw** [comment]
Hi. Thanks for the suggestion. I'll look into that and perhaps discuss with Whisker myself when I have some free time and will add that change eventually. I don't have any imminent plans to make a release because people often just download off of GitHub anyway.

**Pull request merged**
