### PR TITLE
Remove remaining "vgui_cache_res_files 0"

### PR DESCRIPTION
**Pull request by Tiagoquix**
Taking https://github.com/CriticalFlaw/flawhud/issues/361 into consideration, I believe these should be removed as well.

### CODE REVIEW

**Comment by Kruphixx** [comment]
Won't this cause the hud to not refresh properly? Don't think it should be changed

**Comment by CriticalFlaw** [comment]
> Won't this cause the hud to not refresh properly? Don't think it should be changed

Agreed. It's included for a reason. But setting it to 0 does keep it at 0 if you use that button. It should be reverted to 1 at the end of the command.

**Review by CriticalFlaw — CHANGES_REQUESTED** [review]
Instead of removing `vgui_cache_res_files` it should be set to 1 at the end. Same goes for the other file.

**Review by CriticalFlaw — APPROVED** [review]

**Comment by CriticalFlaw** [comment]
Thank you for updating the PR

**Pull request merged**
