### PR TITLE
MVM Menu Clipping 

### PR DESCRIPTION
**Pull request by TheRSO**
Before
image

[look close on 2nd it shows the icon not being transparent]

After

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
You could probably get away with doing the following instead:

1. Move the `mvm_tours.vmt` into the **flawhud/materials/hud**.
2. Delete `mvm_tours.vtf`
3. Add the mvm_tours entry into [flawhud/resource/preload.res](https://github.com/CriticalFlaw/flawhud/blob/master/resource/preload.res)
4. Revert `image` path in **flawhud/resource/ui/mvmcriteria.res** back to "../hud/mvm_tours"

This way it will match the implementation of other files in that same folder and will also make it so that the new image is visible while connected to sv_pure server

**Comment by TheRSO** [comment]
1. If the icon still ends up not being fully transparent, would you like me to delete the vmt as well?

2. In general, what situations should I keep in mind for preloading vmts/vtfs/etc? I’m pretty new to this kind of stuff.

**Comment by CriticalFlaw** [comment]
~~Sorry, i dont quite understand the significance of the transparency. The tours counter being cut off is the issue and i assumed the new icon was resized to help with that~~

**Comment by CriticalFlaw** [comment]
You would typically include any new or updated material files in preload.res so they appear while on sv_pure servers. Otherwise updated materials will revert to default and anything new will appear as a missing texture.

**Comment by CriticalFlaw** [comment]
Oh, sorry i didnt notice the discolouration on the bottom of the icon jn your screenshot

**Comment by TheRSO** [comment]
Yeah it’s more noticeable on desktop. New icon has some buffer around whole icon in case scaling causes clipping and is fully transparent. I can try seeing if the old icon will scale w/o clipping,  when I get the chance. I assume you’re still leaning towards using the og icon?

**Comment by CriticalFlaw** [comment]
I'd like to avoid adding new materials for niche or hard to notice issues. The only exception is if the icon is a complete redesign that fits the theme. But I do like the change to the tour # text so it does not get cut off.

**Comment by TheRSO** [comment]
image
image
Removed the vtf and vmt
Changed `image` path back
Nothing added to preload.res

**Comment by CriticalFlaw** [comment]
Looks great. Thanks!

**Pull request merged**
