### PR TITLE
Update tools.res

### PR DESCRIPTION
**Pull request by Tiagoquix**
Sorry for being rude [here](https://github.com/CriticalFlaw/flawhud/commit/0deb0a74c37d8a646bfb5b7938943e12815fa959). Here are my suggested changes.

### CODE REVIEW

**Review by CriticalFlaw — CHANGES_REQUESTED** [review]
Hi. I looked through your changes and have made some notes. Please the changes then I'll merge them in. Thanks!

- Line 149: Undo this change. `vgui_cache_res_files` should be reapplied in an event that it gets changed during the game session.
- Line 197: Please explain the change in the placement of `closedcaption 1`.
- Line 331: Undo this change. The name becomes inconsistent with the prior buttons. Most users will get the idea that this button toggles chat.
- Lines 375 onward: Undo these changes. Color preferences are up to the individual user, so right now I want to keep these colors as is.

**Comment by Tiagoquix** [comment]
> Hi. I looked through your changes and have made some notes. Please the changes then I'll merge them in. Thanks!
> 
> * Line 149: Undo this change. `vgui_cache_res_files` should be reapplied in an event that it gets changed during the game session.

Please explain better about the line 149. Why would you set this command? If it is very important, it should be added to the valve.rc file.

According to Valve, “[VGUI .res files are now cached after loading, **reducing framerate hitches.** Custom HUD authors can disable this by setting vgui_cache_res_files to 0.](https://www.teamfortress.com/post.php?id=22759)”

> * Line 197: Please explain the change in the placement of `closedcaption 1`.

It was a stylish change. I will revert it.

> * Line 331: Undo this change. The name becomes inconsistent with the prior buttons. Most users will get the idea that this button toggles chat.

That's my idea, toggle the chat. Users would think that "Chat ON/OFF" disables the chat instead of justing hiding it. I agree on keeping the "Chat ON/OFF" labelText if we use the `cl_enable_text_chat` cvar instead.

> * Lines 375 onward: Undo these changes. Color preferences are up to the individual user, so right now I want to keep these colors as is.

I agree that colors are up to the individual user, but we are talking about predefined colors here, colors that can be set by the HUD. With this in mind, the HUD shouldn't set a white color like 89%, 89%, 90% (RGB), like you did. Instead, we should set 100% white (RGB 255, 255, 255). This same idea applies to the other colors.

About changing Blue to Cyan, I can revert that, it's fine.


I will make the changes after your reply.

**Comment by CriticalFlaw** [comment]
> Please explain better about the line 149. Why would you set this command? If it is very important, it should be added to the valve.rc file.

If you set `vgui_cache_res_files 0` only in valve.rc there's a possibility of it being changed to 1 mid-game session. Keeping it in tools.res will ensure that it is always set to 0 before calling `hud_reloadscheme`

> That's my idea, toggle the chat. Users would think that "Chat ON/OFF" disables the chat instead of justing hiding it. I agree on keeping the "Chat ON/OFF" labelText if we use the `cl_enable_text_chat` cvar instead.

I don't think the difference between hiding and disabling chat matters to the general user, but I want to keep the wording similar between options so I'd prefer it to be kept as "Chat ON/OFF"

> I agree that colors are up to the individual user, but we are talking about predefined colors here, colors that can be set by the HUD. With this in mind, the HUD shouldn't set a white color like 89%, 89%, 90% (RGB), like you did. Instead, we should set 100% white (RGB 255, 255, 255). This same idea applies to the other colors.

That's a fair point. You can keep the color changes and keep the button name as Cyan instead of Blue. Also, make sure you change the defaultFgColor_override, armedFgColor_override and depressedFgColor_override values accordingly.

Since we're going ahead with absolute values, we can also add pink (255 0 255) after Cyan. You can it or if not, I'll do it after your PR, just got to make sure all the color buttons are centered. Thanks.

**Review by CriticalFlaw — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by Tiagoquix** [comment]
> > Please explain better about the line 149. Why would you set this command? If it is very important, it should be added to the valve.rc file.
> 
> If you set `vgui_cache_res_files 0` only in valve.rc there's a possibility of it being changed to 1 mid-game session. Keeping it in tools.res will ensure that it is always set to 0 before calling `hud_reloadscheme`

All right. I will set it with the valve.rc too.

> 
> > That's my idea, toggle the chat. Users would think that "Chat ON/OFF" disables the chat instead of justing hiding it. I agree on keeping the "Chat ON/OFF" labelText if we use the `cl_enable_text_chat` cvar instead.
> 
> I don't think the difference between hiding and disabling chat matters to the general user, but I want to keep the wording similar between options so I'd prefer it to be kept as "Chat ON/OFF"
> 

No problem at all. I will use the cl_enable_text_chat cvar then.

> > I agree that colors are up to the individual user, but we are talking about predefined colors here, colors that can be set by the HUD. With this in mind, the HUD shouldn't set a white color like 89%, 89%, 90% (RGB), like you did. Instead, we should set 100% white (RGB 255, 255, 255). This same idea applies to the other colors.
> 
> That's a fair point. You can keep the color changes and keep the button name as Cyan instead of Blue. Also, make sure you change the defaultFgColor_override, armedFgColor_override and depressedFgColor_override values accordingly.
> 
> Since we're going ahead with absolute values, we can also add pink (255 0 255) after Cyan. You can it or if not, I'll do it after your PR, just got to make sure all the color buttons are centered. Thanks.

👍🏻

**Comment by Tiagoquix** [comment]
About hud_saytext_time: instead of changing it to cl_enable_text_chat, I chose to stick with hud_saytext_time. It's better in general, since now I think like you do, @CriticalFlaw, that people will think that the "Chat ON/OFF" button will just hide the chat instead of disabling it entirely.

**Comment by Tiagoquix** [comment]
Done @CriticalFlaw

**Review by CriticalFlaw — APPROVED** [review]
Approved. Thank you for making the changes.

**Pull request merged**
