### PR TITLE
Change minimum FOV in tools

### PR DESCRIPTION
**Pull request by Metisz**
TF2 officially supports up to viewmodel_fov 70 in advanced options, so it only makes sense for the tool to continue from there rather than 75
image
image

### CODE REVIEW

**Comment by Tiagoquix** [comment]
Why not 54-90 then?

**Comment by Metisz** [comment]
> Why not 54-90 then?

I dunno, @CriticalFlaw set it to 75 and then I just wanted the setting to not skip that 5 fov since you can already set it to 70

**Comment by CriticalFlaw** [comment]
I'm going by the wiki that states the official support is 75-90. Where does it say that 70 is the official minimum?

https://wiki.teamfortress.com/wiki/Field_of_View

**Comment by Tiagoquix** [comment]
The Wiki is talking about the `fov_desired` cvar, not `viewmodel_fov`. In the TF2 advanced options menu, the viewmodel FOV can be set from 54 to 70.

**Comment by CriticalFlaw** [comment]
Ah ok. Sure, merged.

**Pull request merged**
