### PR TITLE
Improved KOTH timer visibility when active.

### LINKED ISSUE #244: Low visibility of timers panel backgrounds
image

When not using the match HUD, the timers at the top of the screen are very similar when it comes to their backgrounds' black tone. Could you change them to make them stand out more from each other?

Thanks in advance.

### PR DESCRIPTION
**Pull request by MINIX32**
Fixed #244

### CODE REVIEW

**Comment by MINIX32** [comment]
Might want to change the colors a little or add them to color scheme

**Comment by CriticalFlaw** [comment]
Can you post a screenshot of what this change looks like in-game?

**Comment by MINIX32** [comment]
image

**Comment by Tiagoquix** [comment]
Thanks! Personally, I prefer a black background. Maybe we can change the borders to be team colored.

**Comment by CriticalFlaw** [comment]
I've revised the change to better fit the theme. Let me know what you think.
image

**Comment by Tiagoquix** [comment]
> I've revised the change to better fit the theme. Let me know what you think. image

image
image
image

I've tested them here and they look nice in-game, however:

There seems to be a very small gap between the white line and the border of the timer (weird, because it doesn't show up in your screenshots). I play using the 1366x768 (16:9) resolution.

Also, maybe when the timers are inactive, add a white line in the middle so they stand out better from each other?

**Comment by CriticalFlaw** [comment]
I think the colored timers help separate the two, I may try adding a faded white bar under each timer to make it clear which one is active. Will give that a try today.

**Comment by CriticalFlaw** [comment]
Added a dark line behind the timers to make it easier see the separation when one side is active.
image

**Comment by CriticalFlaw** [comment]
Thank you @MINIX32 and @Tiagoquix for taking a look at this.

**Pull request merged**
