### PR TITLE
Several fixes (mvm, pass time, comp)

### PR DESCRIPTION
**Pull request by impale1**
before

after

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Try to reposition it to be two lines under "Competitive". The third line is touching the border.

**Comment by impale1** [comment]
"MatchmakingBanDurationLabel"
"ypos" "-2"

**Comment by impale1** [comment]
Fixed lack of textures at meters in pass time mode
before

after


Fixed skins being cutoff in mvm upgrade menu
before

after

**Comment by CriticalFlaw** [comment]
> "MatchmakingBanDurationLabel" "ypos" "-2" 

Try adjusting this value because "cooldown for" has enough space to appear on the first line without needing to change the ypos https://github.com/CriticalFlaw/flawhud/blob/132e1c94ec7c38b385e997dee962c2ee4efb0d96/resource/ui/mainmenuplaylistentry.res#L122

**Comment by CriticalFlaw** [comment]
Updated it myself. Looks good. Thank you.

**Pull request merged**
