### PR TITLE
MVM Scoreboard Stats Rework + Minor clipping on main menu

### PR DESCRIPTION
**Pull request by TheRSO**
Added destruction and defenses
Removed redundant stats such as damage/healing/etc which appear on the player list 
Reduced font size slightly to accommodate pro code font clipping issues

Old
image

New
image

### CODE REVIEW

**Comment by TheRSO** [comment]
Before
image
After
image

**Comment by CriticalFlaw** [comment]
I'd like the damage and healing to still be on the scoreboard because otherwise you're forcing the players to open the main menu to see those stats rather than having them all in one place.

**Comment by CriticalFlaw** [comment]
Everything else looks good, so if you could reinstate damage and healing to the scoreboard I'll merge it in. Thanks,

**Comment by TheRSO** [comment]
It's still there? 
image

by default it'd appear twice
image

**Comment by CriticalFlaw** [comment]
Oh right, silly me. That works for me then, Thanks!

**Pull request merged**
